version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongo
