apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ilirjan/restapi
          ports:
            - containerPort: 3000  
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/mydatabase"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000  
      targetPort: 3000  

